# Generated by Django 5.0.1 on 2024-01-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=3000)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Magazine', 'Magazine'), ('Movie', 'Movie')], max_length=30)),
                ('images', models.ImageField(blank=True, upload_to='photos/products')),
                ('seen', models.CharField(max_length=100)),
            ],
        ),
    ]
